package models

import "time"

// IPBan is a global IP ban (manual or auto-generated by the auto-ban engine).
type IPBan struct {
	ID        uint       `gorm:"primaryKey" json:"id"`
	IP        string     `gorm:"uniqueIndex;size:45;not null" json:"ip"`
	Reason    string     `gorm:"size:255" json:"reason"`
	ExpiresAt *time.Time `json:"expires_at"` // nil = permanent
	CreatedAt time.Time  `json:"created_at"`

	// Auto-ban metadata (populated when ban was created automatically by
	// the auto-ban engine — also kept in the table even when set manually,
	// in case an operator wants to inspect what triggered it).
	IsAuto       bool      `gorm:"default:false;index" json:"is_auto"`
	Hits         int       `gorm:"default:0" json:"hits"`
	LastHit      time.Time `json:"last_hit"`
	UserAgent    string    `gorm:"size:512" json:"user_agent"`
	LastPath     string    `gorm:"size:500" json:"last_path"`
	EventType    string    `gorm:"size:50;index" json:"event_type"`     // e.g. bad_api_key
	FirewallRule *uint     `json:"firewall_rule_id"`                    // FK to FirewallRule.ID when we also pushed an iptables rule
}

// IsExpired checks if the ban has expired
func (b *IPBan) IsExpired() bool {
	if b.ExpiresAt == nil {
		return false
	}
	return time.Now().After(*b.ExpiresAt)
}

// LoginAttempt tracks failed login attempts
type LoginAttempt struct {
	ID        uint      `gorm:"primaryKey" json:"id"`
	IP        string    `gorm:"index;size:45;not null" json:"ip"`
	Username  string    `gorm:"index;size:100" json:"username"`
	Success   bool      `gorm:"default:false" json:"success"`
	UserAgent string    `gorm:"size:512" json:"user_agent"`
	CreatedAt time.Time `gorm:"index" json:"created_at"`
}

// SuspiciousEvent records a single suspicious request that may or may not
// have crossed the auto-ban threshold yet. Operators can inspect this log
// to understand attacker behavior.
type SuspiciousEvent struct {
	ID        uint      `gorm:"primaryKey" json:"id"`
	IP        string    `gorm:"index;size:45;not null" json:"ip"`
	EventType string    `gorm:"index;size:50;not null" json:"event_type"` // bad_api_key, bad_origin, bad_ip, rate_limit, bad_login, bad_token
	Method    string    `gorm:"size:10" json:"method"`
	Path      string    `gorm:"size:500" json:"path"`
	UserAgent string    `gorm:"size:512" json:"user_agent"`
	Origin    string    `gorm:"size:255" json:"origin"`
	Details   string    `gorm:"size:1024" json:"details"`
	Banned    bool      `gorm:"default:false;index" json:"banned"` // true if this event triggered (or was after) an auto-ban
	CreatedAt time.Time `gorm:"index" json:"created_at"`
}
